### ISSUE TITLE
Release a new fatbinary version of hitimes with support for ruby 2.2. on windows

### ISSUE THREAD

**Issue by copiousfreetime** [copiousfreetime/hitimes#40]
See issue #39 and http://stackoverflow.com/questions/28985481/hitimes-require-error-when-running-jekyll-serve-on-windows-8-1

**Comment by ccoenen** [comment]
I didn't know the concept of fatbinary until now. Just found a blogpost from tenderlove on the topic, very interesting, thanks! And also thanks for taking care of this issue!

**Comment by copiousfreetime** [comment]
Note to self -- contact https://lukemcgurdy.github.io/jekyll-hitimes-windows-7/ when new version is released.

**Comment by copiousfreetime** [comment]
@andrelugomes @LukeMcGurdy This issue is where I'm tracking the resolution of ruby 2.2 extension

**Comment by LukeMcGurdy** [comment]
Cheers :)

**Comment by andrelugomes** [comment]
@copiousfreetime tks

**Comment by AntiMoron** [comment]
Is ```1.2.2``` the latest version?
seems not working on me while running ```jekyll``` with ```hitimes 1.2.2```.

OS:win7
ruby version : 2.2.2p95
Here's what I got when I do ```jekyll serve```:
```
E:\Projects\antimoron_site>jekyll serve
Configuration file: E:/Projects/antimoron_site/_config.yml
            Source: E:/Projects/antimoron_site
       Destination: E:/Projects/antimoron_site/_site
      Generating...
                    done.
D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': ca
nnot load such file -- hitimes/hitimes (LoadError)
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hi
times.rb:37:in `rescue in <top (required)>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hi
times.rb:32:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in
 `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in
 `rescue in require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers/group.rb
:4:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers.rb:4:in
`<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/r
eceivers.rb:3:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.r
b:475:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/listen-2.10.0/lib/listen.rb:1:in
 `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyll/wa
tcher.rb:26:in `build_listener'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyll/wa
tcher.rb:7:in `watch'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands
/build.rb:68:in `watch'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands
/build.rb:38:in `process'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands
/serve.rb:26:in `block (2 levels) in init_with_program'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/co
mmand.rb:220:in `call'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/co
mmand.rb:220:in `block in execute'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/co
mmand.rb:220:in `each'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/co
mmand.rb:220:in `execute'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/pr
ogram.rb:42:in `go'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb
:19:in `program'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<
top (required)>'
        from D:/Ruby22/bin/jekyll:23:in `load'
        from D:/Ruby22/bin/jekyll:23:in `<main>'
```

**Comment by copiousfreetime** [comment]
@AntiMoron For Ruby 2.2 on windows, you will unfortunately need to need wait until I release a new fat binary.

**Comment by AntiMoron** [comment]
@copiousfreetime   Thank you boss.XD

**Comment by ccoenen** [comment]
not to be rude, but do you have an estimate when you will be releasing an updated gem?

**Comment by NJ-Dev** [comment]
Any update on this issue. I am still getting the same error with ruby 2.2.0 on windows 7.

ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- hitimes/hitimes (LoadError)

**Comment by NJ-Dev** [comment]
I was able to make it work by following the instruction on below link as suggested above. http://stackoverflow.com/questions/28985481/hitimes-require-error-when-running-jekyll-serve-on-windows-8-1

gem uni hitimes
gem ins hitimes -v 1.2.1 --platform ruby

**Comment by aharpervc** [comment]
:+1: still broken

**Comment by stefan-kolb** [comment]
:+1:

**Comment by copiousfreetime** [comment]
@ccoenen @LukeMcGurdy @stefan-kolb @aharpervc @NJ-Dev @AntiMoron @andrelugomes  You will all be happy to know that I have released version 1.2.3 and this issue with jekyll should no longer exist. I did a test install of jekyll on a windows 8 vm and it used the new fatbinary gem (version 1.2.3) and all was well.

Please let me know if you have any other issues down the road. I'll do my best to address them faster than this.

I've managed to get a good windows build system in place so releases for windows will not lag behind the rest of the platforms anymore.

**Comment by stefan-kolb** [comment]
Thanks :+1:

**Comment by andrelugomes** [comment]
nice :)

**Comment by yuessir** [comment]
@copiousfreetime hi ,I reinstall version 1.2.3 ,still broken

**Comment by ccoenen** [comment]
@yuessir could you please be more specific? An error message or a stacktrace perhaps would help tremendously, but steps for how you reached an error will also usually be fine. As far as i can tell, hitimes 1.2.3 works on ruby 2.2.2 32bit with the simple test from #39.

**Comment by ccoenen** [comment]
thanks for providing steps! the error seems to be in `jekyll-redirect-from`, not in hitimes.

**Comment by yuessir** [comment]
@ccoenen Hi
my step
1.install Ruby x64 on Win8.1 
2.install Ruby  DevKit on  Win8.1
3.Install the Jekyll Gem
4.Use Jekyll sample from "huayinthon.github.io"
5.Win Cmd to Folder and run jekyll server

**Comment by ccoenen** [comment]
That looks alright, but in the last line of your previous post, it says 

>  : cannot load such file -- jekyll-redirect-from (LoadError)

And that's why hitimes is (probably) not at fault. jekyll-redirect-from is a project of its own, and it has a bugtracker right here: https://github.com/jekyll/jekyll-redirect-from/issues

**Comment by ccoenen** [comment]
Ah, i may be able to help: try `bundle install` before running the server. You only need to do this once, not every time before starting the server.

**Comment by yuessir** [comment]
@ccoenen  Thanks ,I'll try again

**Comment by copiousfreetime** [comment]
@yuessir I think you need to do `gem install hitimes`. When you add `--platform ruby` that tells rubygems to specifically install the source code version which is not what you want.

In generally when installing ruby gems do not use the `--platform` flag unless you know for sure you want to use it. Rubygems does a pretty good job of installing the appropriate gem for your platform.
